name: machine_2
description: A Flutter app to control a paper counting and stamping machine.

publish_to: 'none' # Remove this line if you plan to publish the app

environment:
  sdk: '>=2.19.0 <4.0.0'  # Add the SDK constraint here

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3  # Add the http package here
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
